'use strict';

const scripts = {
    getCenter : `getCenter`,
    getCenterCode : `getCenterCode`,
    getCustomer: `getCustomer`,
    getCustomerCode : `getCustomerCode`,
    getEmployee : `getEmployee`,
    getEmployeeCode : `getEmployeeCode`,
    getPaymentMode : `getPaymentMode`,
    getExpensive : `getExpensive`,
    getFeedEntry : `getFeedEntry`,
    getPaymentEntry : `getPaymentEntry`,
    getPaymentHistory : `getPaymentHistory`,
    getProduct: `getProduct`,
    getPurchase: `getPurchase`,
    getShift: `getShift`,
    getSupplier: `getSupplier`,
    getSupplierCode: `getSupplierCode`,
    getAdvance: `getAdvance`,
    getPaymentEntryCheck: `getPaymentEntryCheck`,
    getPaymentHistroyCheck: `getPaymentHistroyCheck`,
    getPurchaseDetails: `getPurchaseDetails`,
    getNewPaymentEntry: `getNewPaymentEntry`,
    getEntry: `getEntry`,
    getEntryDetails: `getEntryDetails`,
    getStockHub: `getStockHub`,
    getHubCheck: `getHubCheck`,
    getStockDetails: `getStockDetails`,
    getStockTransferHistory: `getStockTransferHistory`,
    getCheckCenterStock: `getCheckCenterStock`,
    getCommissionSettings: `getCommissionSettings`,
    getCommissionType: `getCommissionType`,
    getSalary: `getSalary`,
    getSalaryEntryDetails: `getSalaryEntryDetails`,
    getTransportSettings: `getTransportSettings`,
    getTransportDriver: `getTransportDriver`,
    getTransportEntry: `getTransportEntry`,
    getTankerSupplier: `getTankerSupplier`,
    getTankerEntry: `getTankerEntry`,
    getCustomerAdvance: `getCustomerAdvance`,
    getCustomerAdvanceHistory: `getCustomerAdvanceHistory`,
    getCustomerSalary: `getCustomerSalary`,
    getUser: `getUser`,
    getRole: `getRole`,
    getRolePermission: `getRolePermission`,
    getPages: `getPages`,
    getCheckCustomerAdvance: `getCheckCustomerAdvance`,
    getFeedEntryHistory: `getFeedEntryHistory`,
    getCheckFeedEntry: `getCheckFeedEntry`,

    getColor: `getColor`,
    getDashboard: `getDashboard`,
    getDashboardDetails: `getDashboardDetails`,
    
};

module.exports = { scripts, };