'use strict';

module.exports = {

  centerTable: {
    "centerId": "center_id",
    "centerName": "center_name",
    "centerCode": "center_code",
    "commissionAmt": "commission_amt",
    "feedCommission": "feed_commission",
    "count": "count",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  customerTable: {
    "customerId": "customer_id",
    "customerName": "customer_name",
    "contactNo": "contact_no",
    "customerCode": "customer_code",
    "bankName": "bank_name",
    "ifsc": "ifsc",
    "count": "count",
    "accountNo": "account_no",
    "branchName": "branch_name",
    "centerId": "center_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  employeeTable: {
    "employeeId": "employee_id",
    "employeeName": "employee_name",
    "contactNo": "contact_no",
    "employeeCode": "employee_code",
    "roleId": "role_id",
    "count": "count",
    "accountNo": "account_no",
    "bankName": "bank_name",
    "ifscCode": "ifsc_code",
    "branchName": "branch_name",
    "centerId": "center_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  paymentModeTable: {
    "paymentModeId": "payment_mode_id",
    "modeName": "mode_name",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  expensiveTable: {
    "expensiveId": "expensive_id",
    "name": "name",
    "description": "description",
    "tax": "tax",
    "amount": "amount",
    "billingDate": "billing_date",
    "purchasedBy": "purchased_by",
    "modePaymentId": "mode_payment_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  feedEntryTable: {
    "feedEntryId": "feed_entry_id",
    "feedEntryDate": "feed_entry_date",
    "amount": "amount",
    "centerId": "center_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  paymentEntryTable: {
    "paymentEntryId": "payment_entry_id",
    "supplierId": "supplier_id",
    "pendingAmt": "pending_amt",
    "paidAmt": "paid_amt",
    "advanceAmt": "advance_amt",
    "lastPayDate": "last_pay_date",
    "paymentHistoryId": "payment_history_id",
    "isAdvance": "is_advance",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  paymentHistoryTable: {
    "paymentHistoryId": "payment_history_id",
    "paidAmount": "paid_amount",
    "balanceAmount": "balance_amount",
    "advanceAmount": "advance_amount",
    "paymentDate": "payment_date",
    "reason": "reason",
    "supplierId": "supplier_id",
    "isAdvance": "is_advance",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  productTable: {
    "productId": "product_id",
    "productName": "product_name",
    "amount": "amount",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  purchaseTable: {
    "purchaseId": "purchase_id",
    "productId": "product_id",
    "qty": "qty",
    "amount": "amount",
    "supplierId": "supplier_id",
    "paidAmount": "paid_amount",
    "transportCharge": "transport_charge",
    "paymentHistoryId": "payment_history_id",
    "purchaseDate": "purchase_date",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  shiftTable: {
    "shiftId": "shift_id",
    "shiftName": "shift_name",
    "shortName": "short_name",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  supplierTable: {
    "supplierId": "supplier_id",
    "supplierName": "supplier_name",
    "contactNo": "contact_no",
    "supplierCode": "supplier_code",
    "branchName": "branch_name",
    "accountNo": "account_no",
    "ifscCode": "ifsc_code",
    "count": "count",
    "bankName": "bank_name",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  entryDetailsTable: {
    "entryDetailsId": "entry_details_id",
    "date": "entry_date",
    "shiftId": "shift_id",
    "centerId": "center_id",
    "customerId": "customer_id",
    "qty": "qty",
    "fat": "fat",
    "snf": "snf",
    "rate": "rate",
    "amount": "amount",
    "entryId": "entry_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  stockHubTable: {
    "stockHubId": "stock_hub_id",
    "totalQty": "total_qty",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  stockDetailsTable: {
    "stockDetailsId": "stock_details_id",
    "transferDate": "transfer_date",
    "centerId": "center_id",
    "totalStock": "total_stock",
    "saleStock": "sale_stock",
    "perQtyAmount": "per_qty_amount",
    "stockHubId": "stock_hub_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  stockTransferHistoryTable: {
    "stockTransferHistoryId": "stock_transfer_history_id",
    "transferDate": "transfer_date",
    "stockQty": "stock_qty",
    "stockDetailsId": "stock_details_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  commissionSettingsTable: {
    "commissionSettingsId": "commission_settings_id",
    "commissionTypeId": "commission_type_id",
    "amount": "amount",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  commissionTypeTable: {
    "commissionTypeId": "commission_type_id",
    "commissionTypeName": "commission_type_name",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  salaryTable: {
    "salaryId": "salary_id",
    "milkCommission": "milk_commission",
    "totalLit": "total_lit",
    "feedCommission": "feed_commission",
    "totalFeed": "total_feed",
    "salaryAmount": "salary_amount",
    "entryDate": "entry_date",
    "employeeId": "employee_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  transportSettingsTable: {
    "transportSettingsId": "transport_settings_id",
    "perKmPrice": "per_km_price",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  transportDriverTable: {
    "transportDriverId": "transport_driver_id",
    "driverName": "driver_name",
    "contactNo": "contact_no",
    "vechileNo": "vechile_no",
    "branchName": "branch_name",
    "ifsc": "ifsc",
    "address": "address",
    "accountNo": "account_no",
    "bankName": "bank_name",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  transportEntryTable: {
    "driverId": "driver_id",
    "km": "km",
    "amount": "amount",
    "deduction": "deduction",
    "deductionReason": "deduction_reason",
    "additionalAmt": "additional_amt",
    "additionalAmtReason": "additional_amt_reason",
    "penalty": "penalty",
    "penaltyReason": "penalty_reason",
    "totalAmt": "total_amt",
    "shiftId": "shift_id",
    "transportIssuse": "transport_issuse",
    "issuseReason": "issuse_reason",
    "alterPersonName": "alter_person_name",
    "alterContactNo": "alter_contact_no",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  tankerSupplierTable: {
    "tankerSupplierId": "tanker_supplier_id",
    "companyName": "company_name",
    "contactPersonName": "contact_person_name",
    "contactNo": "contact_no",
    "registrationNo": "registration_no",
    "gstNo": "gst_no",
    "bankName": "bank_name",
    "branchName": "branch_name",
    "ifsc": "ifsc",
    "accountNo": "account_no",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  tankerEntryTable: {
    "tankerEntryId": "tanker_entry_id",
    "entryDate": "entry_date",
    "quantity": "quantity",
    "amount": "amount",
    "tankerSupplierId": "tanker_supplier_id",
    "driverName": "driver_name",
    "driverContactNo": "driver_contact_no",
    "vehicleNo": "vehicle_no",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  customerAdvanceTable: {
    "customerAdvanceId": "customer_advance_id",
    "totalAmount": "total_amount",
    "paidAmount": "paid_amount",
    "balanceAmount": "balance_amount",
    "customerId": "customer_id",
    "centerId": "center_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  customerAdvanceHistoryTable: {
    "customerAdvanceHistoryId": "customer_advance_history_id",
    "paidAmount": "paid_amount",
    "balanceAmount": "balance_amount",
    "advanceAmount": "advance_amount",
    "paymentDate": "payment_date",
    "reason": "reason",
    "centerId": "center_id",
    "customerId": "customer_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  customerSalaryTable: {
    "customerSalaryId": "customer_salary_id",
    "centerId": "center_id",
    "customerId": "customer_id",
    "fromDate": "from_date",
    "toDate": "to_date",
    "totalLiter": "total_liter",
    "amount": "amount",
    "advance": "advance",
    "feed_amount": "feed_amount",
    "bonus": "bonus",
    "pendingAmount": "pending_amount",
    "totalAmount": "total_amount",
    "isPaid": "is_paid",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  userTable:{
    "userId": "user_id",
    "userName": "user_name",
    "password": "password",
    "token": "token",
    "employeeId": "employee_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",    
  },

  roleTable:{
    "roleId": "role_id",
    "roleName": "role_name",
    "pageIds": "page_ids",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",    
  },

  rolePermissionTable: {
    "rolePermissionId": "role_permission_id",
    "pageId": "page_id",
    "roleId": "role_id",
    "accessIds": "access_ids",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",  
  },

  pagesTable: {
    "pageId": "page_id",
    "pageName": "page_name",
    "title": "title",
    "icons": "icons",
    "path": "path",
    "parentId": "parent_id",
    "accessIds": "access_ids",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",  
  },

  entryTable: {
    "entryId": "entry_id",
    "centerId": "center_id",
    "fromDate": "from_date",
    "toDate": "to_date",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },
}