'use strict';

module.exports = {

  centerTable: {
    "centerId": "center_id",
    "centerName": "center_name",
    "centerCode": "center_code",
    "commissionAmt": "commission_amt",
    "feedCommission": "feed_commission",
    "count": "count",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  customerTable: {
    "customerId": "customer_id",
    "customerName": "customer_name",
    "contactNo": "contact_no",
    "customerCode": "customer_code",
    "bankName": "bank_name",
    "ifsc": "ifsc",
    "count": "count",
    "accountNo": "account_no",
    "branchName": "branch_name",
    "centerId": "center_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  employeeTable: {
    "employeeId": "employee_id",
    "employeeName": "employee_name",
    "contactNo": "contact_no",
    "employeeCode": "employee_code",
    "count": "count",
    "bankName": "bank_name",
    "ifscCode": "ifsc_code",
    "branchName": "branch_name",
    "centerId": "center_id",
    "userName": "user_name",
    "password": "password",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  paymentModeTable: {
    "paymentModeId": "payment_mode_id",
    "modeName": "mode_name",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  expensiveTable: {
    "expensiveId": "expensive_id",
    "name": "name",
    "description": "description",
    "tax": "tax",
    "amount": "amount",
    "billingDate": "billing_date",
    "purchasedBy": "purchased_by",
    "modePaymentId": "mode_payment_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  feedEntryTable: {
    "feedEntryId": "feed_entry_id",
    "feedEntryDate": "feed_entry_date",
    "amount": "amount",
    "centerId": "center_id",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  paymentEntryTable: {
    "paymentEntryId": "payment_entry_id",
    "supplierId": "supplier_id",
    "pendingAmt": "pending_amt",
    "paidAmt": "paid_amt",
    "advanceAmt": "advance_amt",
    "lastPayDate": "last_pay_date",
    "paymentHistoryId": "payment_history_id",
    "isAdvance": "is_advance",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  paymentHistoryTable: {
    "paymentHistoryId": "payment_history_id",
    "paidAmount": "paid_amount",
    "balanceAmount": "balance_amount",
    "advanceAmount": "advance_amount",
    "paymentDate": "payment_date",
    "reason": "reason",
    "supplierId": "supplier_id",
    "isAdvance": "is_advance",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  productTable: {
    "productId": "product_id",
    "productName": "product_name",
    "amount": "amount",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  purchaseTable: {
    "purchaseId": "purchase_id",
    "productId": "product_id",
    "qty": "qty",
    "amount": "amount",
    "supplierId": "supplier_id",
    "paidAmount": "paid_amount",
    "transportCharge": "transport_charge",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  shiftTable: {
    "shiftId": "shift_id",
    "shiftName": "shift_name",
    "shortName": "short_name",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  supplierTable: {
    "supplierId": "supplier_id",
    "supplierName": "supplier_name",
    "contactNo": "contact_no",
    "supplierCode": "supplier_code",
    "branchName": "branch_name",
    "accountNo": "account_no",
    "ifscCode": "ifsc_code",
    "count": "count",
    "bankName": "bank_name",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },

  colorTable: {
    "colorId": "color_id",
    "colorName": "color_name",
    "isActive": "is_active",
    "createdOn": "created_on",
    "updatedOn": "updated_on",
  },
}