'use strict';

module.exports = {
  center: "center",
  customer: "customer",
  employee: "employee",
  paymentMode: "payment_mode",
  expensive: "expensive",
  feedEntry: "feed_entry",
  paymentEntry: "payment_entry",
  paymentHistory: "payment_history",
  product: "product",
  purchase: "purchase",
  shift: "shift",
  supplier: "supplier",
  entry: "entry",
  entryDetails: "entry_details",
  stockHub: "stock_hub",
  stockDetails: "stock_details",
  stockTransferHistory: "stock_transfer_history",
  commissionSettings: "commission_settings",
  commissionType: "commission_type",
  salary: "salary",
  transportSettings: "transport_settings",
  transportDriver: "transport_driver",
  transportEntry: "transport_entry",
  tankerSupplier: "tanker_supplier",
  tankerEntry: "tanker_entry",
  customerAdvance: "customer_advance",
  customerAdvanceHistory: "customer_advance_history",
  customerSalary: "customer_salary",

  rolePermission: "role_permission",
  pages: "pages",
  role: "role",
  user: "users",
  

  color: "color",
}